# Generated by Django 5.2.7 on 2025-11-05 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caretaker',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='caretaker', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('about_me', models.TextField(max_length=800)),
                ('specialisation', models.CharField(max_length=50)),
                ('tel_num', models.CharField(max_length=10)),
            ],
        ),
        migrations.RenameField(
            model_name='student',
            old_name='fakultet',
            new_name='studying_at',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='godina',
            new_name='year_of_study',
        ),
    ]
