# Generated by Django 5.2.7 on 2025-11-06 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_caretaker_rename_fakultet_student_studying_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caretaker',
            name='first_name',
            field=models.CharField(db_index=True, default='IME', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caretaker',
            name='last_name',
            field=models.CharField(db_index=True, default='PREZIME', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='caretaker',
            name='about_me',
            field=models.TextField(blank=True, max_length=800),
        ),
    ]
