# Generated by Django 5.2.7 on 2025-11-11 11:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_caretaker_first_name_caretaker_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='caretaker',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='caretaker',
            name='last_name',
        ),
        migrations.AddField(
            model_name='caretaker',
            name='academic_title',
            field=models.CharField(blank=True, help_text='Professional (academic) title.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='caretaker',
            name='office_address',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='caretaker',
            name='user_image_url',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caretaker',
            name='working_since',
            field=models.PositiveIntegerField(blank=True, help_text='The year in which the person began working as a psychologist.', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='is_anonymous',
            field=models.BooleanField(default=True, help_text="If True, only the student's sex and age will be shown to the caretaker."),
        ),
        migrations.AlterField(
            model_name='caretaker',
            name='tel_num',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='studying_at',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='year_of_study',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE'), ('O', 'OTHER')], default='default_a', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caretaker',
            name='help_categories',
            field=models.ManyToManyField(blank=True, related_name='caretakers', to='accounts.helpcategory'),
        ),
    ]
