# Generated by Django 5.2.8 on 2025-11-11 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='about_me',
            field=models.TextField(blank=True, max_length=800),
        ),
    ]
