# Generated by Django 5.2.8 on 2025-11-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caretaker',
            name='academic_title',
        ),
        migrations.RemoveField(
            model_name='caretaker',
            name='office_address',
        ),
        migrations.RemoveField(
            model_name='caretaker',
            name='user_image_url',
        ),
        migrations.RemoveField(
            model_name='caretaker',
            name='working_since',
        ),
        migrations.RemoveField(
            model_name='student',
            name='is_anonymous',
        ),
        migrations.AddField(
            model_name='caretaker',
            name='first_name',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='caretaker',
            name='last_name',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='about_me',
            field=models.TextField(blank=True, max_length=800),
        ),
        migrations.AlterField(
            model_name='caretaker',
            name='tel_num',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='studying_at',
            field=models.CharField(default='exit', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='year_of_study',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
