# Generated by Django 5.2.7 on 2025-11-12 15:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_student_about_me'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='about_me',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('caretaker', 'Caretaker'), ('student', 'Student')], default='caretaker', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(default=44, validators=[django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
    ]
