# Generated by Django 5.2.7 on 2025-12-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_helpcategory_parent_alter_user_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=60, unique=True),
        ),
    ]
